### ISSUE TITLE
Installation issue with laravel  v5.6.26

### ISSUE THREAD

**Issue by fidel-ruiz** [bold-commerce/bold-shopify-toolkit#76]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install bold-commerce/bold-shopify-toolkit 1.7.2
    - Conclusion: don't install bold-commerce/bold-shopify-toolkit 1.7.1
    - Conclusion: remove laravel/framework v5.6.26
    - Installation request for bold-commerce/bold-shopify-toolkit ^1.7 -> satisfiable by bold-commerce/bold-shopify-toolkit[1.7.0, 1.7.1, 1.7.2].
    - Conclusion: don't install laravel/framework v5.6.26
    - bold-commerce/bold-shopify-toolkit 1.7.0 requires illuminate/support 5.2.* || 5.3.* || 5.4.* || 5.5.* -> satisfiable by illuminate/support[5.2.x-dev, 5.3.x-dev, 5.4.x-dev, 5.5.x-dev, v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5.2.37, v5.2.43, v5.2.45, v5.2.6, v5.2.7, v5.3.0, v5.3.16, v5.3.23, v5.3.4, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40].

**Comment by theRTC204** [comment]
Laravel 5.6 is as yet untested by us, so it's currently not included in the allowed version range. We will investigate.

**Comment by fidel-ruiz** [comment]
Thanks, I just downgrade it, to 5.5.* and is working fine.

**Comment by rickywiens** [comment]
I tried just including 5.6 as an option for illuminate/support and it seems to allow composer to install it. I don't know this package works with it yet though, I still have to run the tests. You can try it out with:

`composer require bold-commerce/bold-shopify-toolkit:dev-explore-56-compat --prefer-source`

**Comment by fidel-ruiz** [comment]
I'll test this after the weekend, I have a hackathon tomorrow with this company and I just assumed this could be used somehow. Maybe it should be included on the wiki section for supported versions.
Anyway thanks again

**Comment by rickywiens** [comment]
https://github.com/bold-commerce/bold-shopify-toolkit/pull/77
